# Generated by Django 3.1.2 on 2022-07-16 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('theme_id', models.AutoField(primary_key=True, serialize=False)),
                ('theme_title', models.CharField(max_length=200)),
                ('theme_contents', models.TextField()),
                ('entered_contents', models.TextField(null=True)),
                ('user_id', models.IntegerField()),
                ('registration_time', models.DateTimeField(default=datetime.datetime.now)),
                ('update_time', models.DateTimeField(null=True)),
                ('last_play_time', models.DateTimeField(null=True)),
                ('num_of_plays', models.IntegerField()),
                ('num_of_contents', models.IntegerField()),
                ('best_record', models.IntegerField(null=True)),
                ('public_flg', models.CharField(max_length=1)),
                ('delete_flg', models.CharField(max_length=1)),
            ],
        ),
    ]
