# Generated by Django 4.0.6 on 2022-07-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('y_line_game_app', '0001_add_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='num_of_incorrect',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='theme',
            name='num_of_remaining_contents',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='play_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='best_record',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='delete_flg',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='theme',
            name='num_of_plays',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='theme',
            name='public_flg',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
