# Generated by Django 4.0.6 on 2022-08-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('y_line_game_app', '0002_add_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='num_of_entered_contents',
            field=models.IntegerField(default=0),
        ),
    ]
