# Generated by Django 4.0.6 on 2022-08-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('y_line_game_app', '0004_add_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='entered_contents',
            field=models.TextField(default='', null=True),
        ),
    ]
