# Generated by Django 4.0.6 on 2022-08-14 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('y_line_game_app', '0005_add_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('registration_time', models.DateTimeField(default=datetime.datetime.now)),
                ('update_time', models.DateTimeField(null=True)),
                ('delete_flg', models.CharField(default=0, max_length=1)),
            ],
        ),
    ]
