# Generated by Django 4.0.6 on 2022-08-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('y_line_game_app', '0006_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_flg',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
