# Generated by Django 4.0.6 on 2022-08-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('y_line_game_app', '0007_add_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
