# Generated by Django 4.0.6 on 2022-08-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('y_line_game_app', '0009_add_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='num_of_clear',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
